[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["./day-01", "./day-02"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
